---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./angelnu.yaml
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./descheduler.yaml
  - ./external-dns.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./kubereboot.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
  - ./xenitab.yaml
