apiVersion: v1
kind: Secret
metadata:
    name: indexer-secrets
    namespace: mymindinai-dev
type: Opaque
stringData:
    AWS_REGION: ENC[AES256_GCM,data:Vlm6MTaJuWRB,iv:IsuVukMIiajys88VlY/twXJXzPNQjjrjz8moSFdmAEw=,tag:V8nbQBKb3ulPpUcQczlvZQ==,type:str]
    SQS_URL: ENC[AES256_GCM,data:r0nfECA8yexjYz7C6LAxPpJnRKCRzjJj8a+qpDZw1SmD72VT+5y65N2JY47jxEsc83WUxyapuCQrAB3lfHThH1M2pUHv0ncM1g==,iv:0+dbaCaVGfBJuSAMIl8MKQjEwD8oMcdUCFAVoKFGmpY=,tag:78DZ1lyFab8U3TaET/gZcA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:2CBtjgu/Obs3On+opUgBZSu+O19xRzb/XmmIrcQhwE22yV0UM+g5uUGOVZvpX0MGd/SuPqqDgsMyTgaDEFq3HPKXpjOP8ZCnJLeIm7KCn4oqPazqWGow8lSNwh0=,iv:IPQ276vG0fH8rdl1qI41brBxRD1qQ8H8kFb5jNTmrQM=,tag:R7LdL5emo4w/EXabIL65EQ==,type:str]
sops:
    age:
        - recipient: age12rzrdtn8xhd89y23qw4kymxftuylqn5cm522jcn327atent4a40swjcgmj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOEFPelN2VXE2c1J5aUMx
            R2VkTDVuQ0dXVXpVL0hnUUhvRUFEK2FMWkNBCm04eldsdG5qN0luZUkxVzJhZmlN
            U1lkQUJqRk9DS2UxNlhuR3JtZXZjWlkKLS0tIHJrcTAvNXlkdTY3VndSNkFRaHFI
            ckcwQjRXR3c0UkJSM21uWSs2YStMMUUK16WYOaBdHVL2ajALLZTJ46UvWHfTlPEc
            p5s3eZrd7iPoYPIIB1RmFqGuw57eQh0cp6Sk4sqZl3h1EXfVGpiVpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T05:04:21Z"
    mac: ENC[AES256_GCM,data:PknexPyx3YzSamT61Ta9AIxE9stqLX4b4sm1vO8q1TX6LXhd5c+mALBkEONWOqy4/NTS9xlYPzTPA88aD+rw7h9D8W1M+YScN4l3yHduWXEHH5D0llg33XKi0z1fAZmWiE//YRHZz6JfuKf7aTUonX949cspXD9kQGYmXp78mtw=,iv:Th9QjNHlTzt8bIDKjdlyVSe9JaFH3m69IxQidYMDgf8=,tag:Iq56QeszNJdwQLZ0wLUdeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
